
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-08
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-08
pull_requests: [{"author":{"id":"U_kgDOCN6bmA","is_bot":false,"login":"emilylaoo","name":""},"headRefName":"Emily-H2Connections","number":21,"title":"Emily: added line to app-dev properties file to enable multiple H2 connections","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-08/pull/21"}]
