
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-08
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-08
pull_requests: [{"author":{"id":"MDQ6VXNlcjE1OTcwNTcw","is_bot":false,"login":"dalidog","name":"Dalia Sebat"},"headRefName":"Dalia-Alias-Table","number":29,"title":"DS - FEATURE: Add an Alias Approval Table","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-08/pull/29"},{"author":{"id":"U_kgDOCVHSlQ","is_bot":false,"login":"DengLucy","name":""},"headRefName":"ld-change-to-absolute-path","number":24,"title":"ld - change to absolute path","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-08/pull/24"},{"author":{"id":"U_kgDOCVHSlQ","is_bot":false,"login":"DengLucy","name":""},"headRefName":"ld-delete-placeholder","number":23,"title":"ld - delete placeholder","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-08/pull/23"},{"author":{"id":"U_kgDOCVHSlQ","is_bot":false,"login":"DengLucy","name":""},"headRefName":"ld-review-endpoint","number":22,"title":"ld - Added a GET endpoint for review","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-08/pull/22"}]
